create table problem (
	id bigint generated by default as identity primary key,
	title varchar(200) not null,
	statement text not null,
	difficulty varchar(20) not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table problem_tag (
	id bigint generated by default as identity primary key,
	name varchar(80) not null unique
);

create table problem_tag_link (
	problem_id bigint not null references problem(id) on delete cascade,
	tag_id bigint not null references problem_tag(id) on delete cascade,
	primary key (problem_id, tag_id)
);

create table problem_example (
	id bigint generated by default as identity primary key,
	problem_id bigint not null references problem(id) on delete cascade,
	input_text text not null,
	output_text text not null,
	explanation text,
	sort_order int not null
);

create table problem_solution (
	id bigint generated by default as identity primary key,
	problem_id bigint not null references problem(id) on delete cascade,
	language varchar(20) not null,
	content text not null,
	explanation text
);

create table test_case (
	id bigint generated by default as identity primary key,
	problem_id bigint not null references problem(id) on delete cascade,
	input_text text not null,
	expected_output_text text not null,
	is_sample boolean not null,
	sort_order int not null
);

create table contest (
	id bigint generated by default as identity primary key,
	title varchar(200) not null,
	description text,
	start_time timestamp with time zone not null,
	end_time timestamp with time zone not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table contest_problem (
	id bigint generated by default as identity primary key,
	contest_id bigint not null references contest(id) on delete cascade,
	problem_id bigint not null references problem(id) on delete restrict,
	position int not null,
	points int not null,
	constraint uq_contest_problem unique (contest_id, problem_id),
	constraint uq_contest_position unique (contest_id, position)
);

create table contest_registration (
	id bigint generated by default as identity primary key,
	contest_id bigint not null references contest(id) on delete cascade,
	user_id varchar(120) not null,
	registered_at timestamp with time zone not null,
	constraint uq_contest_registration unique (contest_id, user_id)
);

create table submission (
	id bigint generated by default as identity primary key,
	user_id varchar(120) not null,
	problem_id bigint not null references problem(id) on delete restrict,
	contest_id bigint references contest(id) on delete set null,
	language varchar(20) not null,
	code text not null,
	verdict varchar(20) not null,
	score int,
	created_at timestamp with time zone not null
);

create table visualizer_snapshot (
	id bigint generated by default as identity primary key,
	submission_id bigint not null references submission(id) on delete cascade,
	snapshot_index int not null,
	payload text not null,
	created_at timestamp with time zone not null,
	constraint uq_snapshot unique (submission_id, snapshot_index)
);

create index idx_problem_difficulty on problem(difficulty);
create index idx_problem_title on problem(title);
create index idx_contest_start on contest(start_time);
create index idx_submission_user on submission(user_id);
